---
# file: apache/tasks/build.yml
#
# build tasks.
#

- name: build | ensure the build dependencies are present
  apt:
    name="{{ item }}"
    state=present
  become: yes
  with_items: "{{ apache_build_dependencies }}"

- name: build | download tarball
  get_url:
    url="{{ apache_download_url }}"
    dest="{{ apache_dir_source }}/{{ apache_tarball }}"
    owner="{{ ansible_env.USER }}"
    group="{{ ansible_env.USER }}"
    mode=0440
    checksum="md5:{{ apache_download_url_md5 }}"
  become: yes
  register: task_apache_download

- name: build | unarchive tarball
  unarchive:
    src="{{ apache_dir_source }}/{{ apache_tarball }}"
    dest="{{ apache_dir_source }}"
    copy=no
    owner="{{ ansible_env.USER }}"
    group="{{ ansible_env.USER }}"
  when: task_apache_download.changed
  become: yes

- name: build | configure
  command: "./configure {{ apache_build_options }}"
  args:
    chdir: "{{ apache_dir_source }}/apache-{{ apache_version }}"
  when: task_apache_download.changed

- name: build | build
  command: make
  args:
    chdir: "{{ apache_dir_source }}/apache-{{ apache_version }}"
  when: task_apache_download.changed

- name: build | install
  command: make install
  args:
    chdir: "{{ apache_dir_source }}/apache-{{ apache_version }}"
  become: yes
  when: task_apache_download.changed
