---
# file: apache/tasks/configuration.yml
#
# configuration tasks.
#

- name: configuration | setup /usr/local/apache2 directory link
  file:
    src="/usr/local/apache2-{{ apache_version }}"
    path=/usr/local/apache2
    state=link
  become: yes

- name: configuration | setup modules directory link
  file:
    src=/usr/local/apache2/modules
    path="{{ apache_dir_modules }}"
    state=link
  become: yes

- name: configuration | setup configuration directories
  file:
    path="{{ apache_dir_configuration }}{{ item }}"
    owner="{{ apache_user.name }}"
    group="{{ apache_user.name }}"
    mode=0750
    state=directory
  become: yes
  with_items:
    - ''
    - /conf-available
    - /mods-available
    - /mods-enabled
    - /sites-available
    - /sites-enabled

- name: configuration | service default
  template:
    src=etc/default/apache2.j2
    dest=/etc/default/apache2
    owner=root
    group=root
    mode=0644
  become: yes

- name: configuration | service environment variables
  template:
    src=etc/apache2/envvars.j2
    dest=/etc/apache2/envvars
    owner=root
    group=root
    mode=0644
  become: yes
