---
# file: apache/tasks/configuration.yml
#
# configuration tasks.
#

- name: configuration | setup /usr/local/httpd directory link
  file:
    src="/usr/local/httpd-{{ httpd_version }}"
    path=/usr/local/httpd
    state=link
  become: yes
  notify: restart httpd

- name: configuration | setup modules directory link
  file:
    src=/usr/local/httpd/modules
    path="{{ httpd_dir_lib }}"
    state=link
  become: yes
  notify: restart httpd

- name: configuration | setup configuration directories
  file:
    path="{{ httpd_dir_configuration }}{{ item }}"
    owner="{{ httpd_user.name }}"
    group="{{ httpd_user.name }}"
    mode=0750
    state=directory
  become: yes
  with_items:
    - ''
    - /conf-available
    - /conf-enabled
    - /mods-available
    - /mods-enabled
    - /sites-available
    - /sites-enabled
  notify: restart httpd

- name: configuration | setup other directories
  file:
    path="{{ item }}"
    owner="{{ httpd_user.name }}"
    group="{{ httpd_user.name }}"
    mode=0755
    state=directory
  become: yes
  with_items:
    - "{{ httpd_dir_cache }}"
    - "{{ httpd_dir_lock }}"
    - "{{ httpd_dir_log }}"
    - "{{ httpd_dir_run }}"

- name: configuration | /etc/default/httpd
  template:
    src=etc/default/httpd.j2
    dest=/etc/default/httpd
    owner="{{ httpd_user.name }}"
    group="{{ httpd_user.name }}"
    mode=0644
  become: yes
  notify: restart httpd

- name: configuration | /etc/httpd/httpd.conf
  template:
    src=etc/httpd/httpd.conf.j2
    dest=/etc/httpd/httpd.conf
    owner="{{ httpd_user.name }}"
    group="{{ httpd_user.name }}"
    mode=0644
  become: yes
  notify: restart httpd

- name: configuration | /etc/httpd/ports.conf
  template:
    src=etc/httpd/ports.conf.j2
    dest=/etc/httpd/ports.conf
    owner="{{ httpd_user.name }}"
    group="{{ httpd_user.name }}"
    mode=0644
  become: yes
  notify: restart httpd

- name: configuration | /etc/init.d/httpd
  template:
    src=etc/init.d/httpd.j2
    dest=/etc/init.d/httpd
    owner=root
    group=root
    mode=0755
  become: yes
  notify: restart httpd
