---
# file: apache/tasks/configuration.yml
#
# configuration tasks.
#

- name: configuration | setup /usr/local/httpd directory link
  file:
    src="/usr/local/httpd-{{ httpd_version }}"
    path=/usr/local/httpd
    state=link
  become: yes

- name: configuration | setup modules directory link
  file:
    src=/usr/local/httpd/modules
    path="{{ httpd_dir_lib }}"
    state=link
  become: yes

- name: configuration | setup configuration directories
  file:
    path="{{ httpd_dir_configuration }}{{ item }}"
    owner="{{ httpd_user.name }}"
    group="{{ httpd_user.name }}"
    mode=0750
    state=directory
  become: yes
  with_items:
    - ''
    - /conf-available
    - /mods-available
    - /mods-enabled
    - /sites-available
    - /sites-enabled

- name: configuration | service default
  template:
    src=etc/default/httpd.j2
    dest=/etc/default/httpd
    owner=root
    group=root
    mode=0644
  become: yes

- name: configuration | service environment variables
  template:
    src=etc/httpd/envvars.j2
    dest=/etc/httpd/envvars
    owner=root
    group=root
    mode=0644
  become: yes

- name: configuration | service ports
  template:
    src=etc/httpd/ports.conf.j2
    dest=/etc/httpd/ports.conf
    owner=root
    group=root
    mode=0644
  become: yes
