---
# file: tasks/debug.yml
#
# debug tasks.
#

- debug:
    var="{{ item }}"
  when: "{{ item }} is defined"
  with_items:
    - httpd_build_dependencies
    - httpd_build_options
    - httpd_configuration
    - httpd_default
    - httpd_dir
    - httpd_dir_cache
    - httpd_dir_configuration
    - httpd_dir_install
    - httpd_dir_lock
    - httpd_dir_lib
    - httpd_dir_run
    - httpd_dir_source
    - httpd_download_url
    - httpd_download_url_asc
    - httpd_download_url_md5
    - httpd_env
    - httpd_force_build
    - httpd_modules
    - httpd_modules_enabled
    - httpd_ports
    - httpd_user.name
    - httpd_version
