---
# file: apache/tasks/main.yml
#
# tasks file
#

- include: debug.yml
  when: debug | default(false)
  tags: debug

- name: setup apache account
  user:

  become: yes

- include: validation.yml
  tags: validation

- include: build.yml
  tags: build

- include: configuration.yml
  tags: configuration

- include: modules.yml
  tags: modules
