---
# file: apache/tasks/main.yml
#
# tasks file
#

- include: debug.yml
  when: debug | default(false)
  tags: debug

- name: setup apache account
  user:
    name="{{ apache_user.name }}"
    home="{{ apache_user.home }}"
    shell="{{ apache_user.shell }}"
    uid="{{ apache_user.uid| default(None) }}"
    system=yes
    state=present
  become: yes

- include: validation.yml
  tags: validation

- include: build.yml
  tags: build

- include: configuration.yml
  tags: configuration

- include: modules.yml
  tags: modules
