---
# file: apache/tasks/modules.yml
#
# module configuration tasks.
#

- name: modules | setup /etc/httpd/mods-available .load files
  template:
    src=etc/httpd/mods-available/mod.load.j2
    dest="{{ httpd_dir_configuration }}/mods-available/{{ item }}.load"
    owner="{{ httpd_user.name }}"
    group="{{ httpd_user.name }}"
    mode=0644
  with_items: "{{ httpd_modules }}"
  when: "{{  }}"
  become: yes

- name: modules | enable modules
  file:
    src="/etc/httpd/mods-available/{{ item.name }}.load"
    dest="/etc/httpd/mods-enabled/{{ item.name }}.load"
    state=link
  with_items: "{{ httpd_modules_enabled }}"
  when: "{{ item.enabled and item.dynamic|default(true) }}"
  become: yes

- name: modules | disable modules (.load)
  file:
    path="/etc/httpd/mods-enabled/{{ item.name }}.load"
    state=absent
  with_items: "{{ httpd_modules_enabled }}"
  when: "{{ not item.enabled }}"
  become: yes

- name: modules | disable modules (.conf)
  file:
    path="/etc/httpd/mods-enabled/{{ item.name }}.conf"
    state=absent
  with_items: "{{ httpd_modules_enabled }}"
  when: "{{ not item.enabled }}"
  become: yes

- name: modules | setup enabled modules
  template:
    src=etc/httpd/mods-enabled/mod.conf.j2
    dest="{{ httpd_dir_configuration }}/mods-enabled/{{ item.name }}.conf"
    owner="{{ httpd_user.name }}"
    group="{{ httpd_user.name }}"
    mode=0644
  with_items: "{{ httpd_modules_enabled }}"
  when: "{{ item.enabled }}"
  become: yes
