---
# file: apache/tasks/modules.yml
#
# module configuration tasks.
#

- name: modules | setup /usr/local/apache2 directory link
  template:
    src=etc/apache2/mods-available/mod.load.j2
    dest="{{ apache_dir_configuration }}/mods-available/{{ item }}.load"
    owner="{{ apache_user.name }}"
    group="{{ apache_user.name }}"
    mode=0644
  with_items: "{{ apache_modules }}"
  become: yes
