---
# file: httpd/tasks/modules.yml
#
# module configuration tasks.
#

- name: modules | setup static modules configuration
  template:
    src=etc/httpd/mods-enabled/mod_static.conf.j2
    dest="{{ httpd_dir_configuration }}/mods-enabled/{{ item.name }}.conf"
    owner=root
    group=root
    mode=0644
  with_items: "{{ httpd_modules_static }}"
  when: "{{ item.enabled and item.configuration is defined }}"
  become: yes

- name: modules | setup /etc/httpd/mods-available .load files
  template:
    src=etc/httpd/mods-available/mod.load.j2
    dest="{{ httpd_dir_configuration }}/mods-available/{{ item }}.load"
    owner=root
    group=root
    mode=0644
  with_items: "{{ httpd_modules }}"
  become: yes

- name: modules | enable dynamic modules
  file:
    src="{{ httpd_dir_configuration }}/mods-available/{{ item.name }}.load"
    dest="{{ httpd_dir_configuration }}/mods-enabled/{{ item.name }}.load"
    state=link
  with_items: "{{ httpd_modules_dynamic }}"
  when: "{{ item.enabled }}"
  become: yes

- name: modules | setup dynamic modules configuration
  template:
    src=etc/httpd/mods-enabled/mod_dynamic.conf.j2
    dest="{{ httpd_dir_configuration }}/mods-enabled/{{ item.name }}.conf"
    owner=root
    group=root
    mode=0644
  with_items: "{{ httpd_modules_dynamic }}"
  when: "{{ item.enabled and item.configuration is defined }}"
  become: yes

- name: modules | disable dynamic modules
  file:
    path="{{ httpd_dir_configuration }}/mods-enabled/{{ item.name }}.load"
    state=absent
  with_items: "{{ httpd_modules_dynamic }}"
  when: "{{ not item.enabled }}"
  become: yes

- name: modules | remove dynamic modules configuration
  file:
    path="{{ httpd_dir_configuration }}/mods-enabled/{{ item.name }}.conf"
    state=absent
  with_items: "{{ httpd_modules_dynamic }}"
  when: "{{ not item.enabled }}"
  become: yes

- name: modules | remove static modules configuration
  file:
    path="{{ httpd_dir_configuration }}/mods-enabled/{{ item.name }}.conf"
    state=absent
  with_items: "{{ httpd_modules_static }}"
  when: "{{ not item.enabled }}"
  become: yes
