---
# file: apache/tasks/modules.yml
#
# module configuration tasks.
#

- name: modules | setup /usr/local/httpd directory link
  template:
    src=etc/httpd/mods-available/mod.load.j2
    dest="{{ httpd_dir_configuration }}/mods-available/{{ item }}.load"
    owner="{{ httpd_user.name }}"
    group="{{ httpd_user.name }}"
    mode=0644
  with_items: "{{ httpd_modules }}"
  become: yes
