---
# file: httpd/tasks/package/validation.yml
#
# package validation tasks.
#

- name: package | validation | ensure mandatory variables are set
  fail:
    msg="{{ item }} is a mandatory variable"
  when: "{{ item }} is not defined"
  with_items:
    - httpd_configuration
    - httpd_dir_configuration
    - httpd_installation
    - httpd_service
    - httpd_user
    - httpd_user.name
